### PR TITLE
mainnet deployments

### PR DESCRIPTION
**Pull request by hrishikeshio**

### CODE REVIEW

**Comment by yohanelly95** [comment]
we will test the mainnet deployments and merge this PR accordingly cc @hrishikeshio @rajkharvar @SamAg19

**Comment by hrishikeshio** [comment]
> we will test the mainnet deployments and merge this PR accordingly cc @hrishikeshio @rajkharvar @SamAg19 

Update?

**Comment by yohanelly95** [comment]
> > we will test the mainnet deployments and merge this PR accordingly cc @hrishikeshio @rajkharvar @SamAg19
> 
> Update?

Test a Client Contract on all the mainnet chains successfully, only XDC was facing an error on remix. Will debug this and share an update @hrishikeshio

**Comment by hrishikeshio** [comment]
No need to block whole pr for 1 network. You can merge the rest.

**Review by ashish10677 — APPROVED** [review]

**Review by yohanelly95 — APPROVED** [review]

**Comment by yohanelly95** [comment]
cannot merge this PR since there are unsigned commits. Will recreate this PR and merge it. cc @hrishikeshio @SamAg19

**Comment by yohanelly95** [comment]
the changes are added to #92

**Pull request closed without merging**
